### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by bpstewar** [worldbank/GEE_Zonal#9]
**Describe the bug**
Running the install commands using the environment.yml resulted in un resolved packages

**To Reproduce**
Run the install instructions on landing page

**Screenshots**
![image](https://user-images.githubusercontent.com/5446296/122437081-5f287480-cf67-11eb-8ecc-f4a851527118.png)

**Desktop (please complete the following information):**
 - OS: Linux (JNB)

**Additional context**

**Comment by andresfchamorro** [comment]
Closing this as installation has been updated https://github.com/worldbank/GEE_Zonal/pull/13
